# FIFA World Cup 2026 - Complete Fixture List
# All 104 matches verified from official FIFA draw (5 December 2025) and confirmed schedule.
# Group-stage times are in each venue's LOCAL time (as officially published).
# Knockout-stage teams use official FIFA bracket labels (filled in during tournament play).
#
# Venue official names used during the tournament:
#   Estadio Azteca          – Mexico City, Mexico
#   Estadio Akron           – Zapopan (Guadalajara), Mexico
#   Estadio BBVA            – Guadalupe (Monterrey), Mexico
#   BMO Field               – Toronto, Canada
#   BC Place                – Vancouver, Canada
#   SoFi Stadium            – Inglewood (Los Angeles), USA
#   Levi's Stadium          – Santa Clara (San Francisco Bay Area), USA
#   Lumen Field             – Seattle, USA
#   NRG Stadium             – Houston, USA
#   AT&T Stadium            – Arlington (Dallas), USA
#   Arrowhead Stadium       – Kansas City, USA
#   Gillette Stadium        – Foxborough (Boston), USA
#   Lincoln Financial Field – Philadelphia, USA
#   Hard Rock Stadium       – Miami Gardens (Miami), USA
#   Mercedes-Benz Stadium   – Atlanta, USA
#   MetLife Stadium         – East Rutherford (New York / New Jersey), USA

FIXTURES = [
    # ──────────────────────────────────────────────────────────────────
    # GROUP STAGE  (Matches 1–72)
    # ──────────────────────────────────────────────────────────────────

    # Thursday 11 June 2026
    {
        "match_no": 1,
        "date": "2026-06-11",
        "time": "13:00",
        "stage": "Group A",
        "group": "A",
        "team1": "Mexico",
        "team2": "South Africa",
        "venue": "Estadio Azteca",
        "city": "Mexico City",
        "country": "Mexico",
    },
    {
        "match_no": 2,
        "date": "2026-06-11",
        "time": "20:00",
        "stage": "Group A",
        "group": "A",
        "team1": "South Korea",
        "team2": "Czechia",
        "venue": "Estadio Akron",
        "city": "Zapopan",
        "country": "Mexico",
    },

    # Friday 12 June 2026
    {
        "match_no": 3,
        "date": "2026-06-12",
        "time": "15:00",
        "stage": "Group B",
        "group": "B",
        "team1": "Canada",
        "team2": "Bosnia and Herzegovina",
        "venue": "BMO Field",
        "city": "Toronto",
        "country": "Canada",
    },
    {
        "match_no": 4,
        "date": "2026-06-12",
        "time": "18:00",
        "stage": "Group D",
        "group": "D",
        "team1": "United States",
        "team2": "Paraguay",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },

    # Saturday 13 June 2026
    {
        "match_no": 5,
        "date": "2026-06-13",
        "time": "12:00",
        "stage": "Group B",
        "group": "B",
        "team1": "Qatar",
        "team2": "Switzerland",
        "venue": "Levi's Stadium",
        "city": "Santa Clara",
        "country": "USA",
    },
    {
        "match_no": 6,
        "date": "2026-06-13",
        "time": "18:00",
        "stage": "Group C",
        "group": "C",
        "team1": "Brazil",
        "team2": "Morocco",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 7,
        "date": "2026-06-13",
        "time": "21:00",
        "stage": "Group C",
        "group": "C",
        "team1": "Haiti",
        "team2": "Scotland",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },
    {
        "match_no": 8,
        "date": "2026-06-13",
        "time": "21:00",
        "stage": "Group D",
        "group": "D",
        "team1": "Australia",
        "team2": "Turkey",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },

    # Sunday 14 June 2026
    {
        "match_no": 9,
        "date": "2026-06-14",
        "time": "12:00",
        "stage": "Group E",
        "group": "E",
        "team1": "Germany",
        "team2": "Curaçao",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 10,
        "date": "2026-06-14",
        "time": "15:00",
        "stage": "Group F",
        "group": "F",
        "team1": "Netherlands",
        "team2": "Japan",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 11,
        "date": "2026-06-14",
        "time": "19:00",
        "stage": "Group E",
        "group": "E",
        "team1": "Ivory Coast",
        "team2": "Ecuador",
        "venue": "Lincoln Financial Field",
        "city": "Philadelphia",
        "country": "USA",
    },
    {
        "match_no": 12,
        "date": "2026-06-14",
        "time": "20:00",
        "stage": "Group F",
        "group": "F",
        "team1": "Sweden",
        "team2": "Tunisia",
        "venue": "Estadio BBVA",
        "city": "Guadalupe",
        "country": "Mexico",
    },

    # Monday 15 June 2026
    {
        "match_no": 13,
        "date": "2026-06-15",
        "time": "12:00",
        "stage": "Group H",
        "group": "H",
        "team1": "Spain",
        "team2": "Cape Verde",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 14,
        "date": "2026-06-15",
        "time": "12:00",
        "stage": "Group G",
        "group": "G",
        "team1": "Belgium",
        "team2": "Egypt",
        "venue": "Lumen Field",
        "city": "Seattle",
        "country": "USA",
    },
    {
        "match_no": 15,
        "date": "2026-06-15",
        "time": "18:00",
        "stage": "Group H",
        "group": "H",
        "team1": "Saudi Arabia",
        "team2": "Uruguay",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },
    {
        "match_no": 16,
        "date": "2026-06-15",
        "time": "18:00",
        "stage": "Group G",
        "group": "G",
        "team1": "Iran",
        "team2": "New Zealand",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },

    # Tuesday 16 June 2026
    {
        "match_no": 17,
        "date": "2026-06-16",
        "time": "15:00",
        "stage": "Group I",
        "group": "I",
        "team1": "France",
        "team2": "Senegal",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 18,
        "date": "2026-06-16",
        "time": "18:00",
        "stage": "Group I",
        "group": "I",
        "team1": "Iraq",
        "team2": "Norway",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },
    {
        "match_no": 19,
        "date": "2026-06-16",
        "time": "20:00",
        "stage": "Group J",
        "group": "J",
        "team1": "Argentina",
        "team2": "Algeria",
        "venue": "Arrowhead Stadium",
        "city": "Kansas City",
        "country": "USA",
    },
    {
        "match_no": 20,
        "date": "2026-06-16",
        "time": "21:00",
        "stage": "Group J",
        "group": "J",
        "team1": "Austria",
        "team2": "Jordan",
        "venue": "Levi's Stadium",
        "city": "Santa Clara",
        "country": "USA",
    },

    # Wednesday 17 June 2026
    {
        "match_no": 21,
        "date": "2026-06-17",
        "time": "12:00",
        "stage": "Group K",
        "group": "K",
        "team1": "Portugal",
        "team2": "DR Congo",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 22,
        "date": "2026-06-17",
        "time": "15:00",
        "stage": "Group L",
        "group": "L",
        "team1": "England",
        "team2": "Croatia",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 23,
        "date": "2026-06-17",
        "time": "19:00",
        "stage": "Group L",
        "group": "L",
        "team1": "Ghana",
        "team2": "Panama",
        "venue": "BMO Field",
        "city": "Toronto",
        "country": "Canada",
    },
    {
        "match_no": 24,
        "date": "2026-06-17",
        "time": "20:00",
        "stage": "Group K",
        "group": "K",
        "team1": "Uzbekistan",
        "team2": "Colombia",
        "venue": "Estadio Azteca",
        "city": "Mexico City",
        "country": "Mexico",
    },

    # Thursday 18 June 2026
    {
        "match_no": 25,
        "date": "2026-06-18",
        "time": "12:00",
        "stage": "Group A",
        "group": "A",
        "team1": "Czechia",
        "team2": "South Africa",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 26,
        "date": "2026-06-18",
        "time": "12:00",
        "stage": "Group B",
        "group": "B",
        "team1": "Switzerland",
        "team2": "Bosnia and Herzegovina",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },
    {
        "match_no": 27,
        "date": "2026-06-18",
        "time": "15:00",
        "stage": "Group B",
        "group": "B",
        "team1": "Canada",
        "team2": "Qatar",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },
    {
        "match_no": 28,
        "date": "2026-06-18",
        "time": "19:00",
        "stage": "Group A",
        "group": "A",
        "team1": "Mexico",
        "team2": "South Korea",
        "venue": "Estadio Akron",
        "city": "Zapopan",
        "country": "Mexico",
    },

    # Friday 19 June 2026
    {
        "match_no": 29,
        "date": "2026-06-19",
        "time": "12:00",
        "stage": "Group D",
        "group": "D",
        "team1": "United States",
        "team2": "Australia",
        "venue": "Lumen Field",
        "city": "Seattle",
        "country": "USA",
    },
    {
        "match_no": 30,
        "date": "2026-06-19",
        "time": "18:00",
        "stage": "Group C",
        "group": "C",
        "team1": "Scotland",
        "team2": "Morocco",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },
    {
        "match_no": 31,
        "date": "2026-06-19",
        "time": "21:00",
        "stage": "Group D",
        "group": "D",
        "team1": "Turkey",
        "team2": "Paraguay",
        "venue": "Levi's Stadium",
        "city": "Santa Clara",
        "country": "USA",
    },
    {
        "match_no": 32,
        "date": "2026-06-19",
        "time": "20:30",
        "stage": "Group C",
        "group": "C",
        "team1": "Brazil",
        "team2": "Haiti",
        "venue": "Lincoln Financial Field",
        "city": "Philadelphia",
        "country": "USA",
    },

    # Saturday 20 June 2026
    {
        "match_no": 33,
        "date": "2026-06-20",
        "time": "12:00",
        "stage": "Group F",
        "group": "F",
        "team1": "Netherlands",
        "team2": "Sweden",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 34,
        "date": "2026-06-20",
        "time": "16:00",
        "stage": "Group E",
        "group": "E",
        "team1": "Germany",
        "team2": "Ivory Coast",
        "venue": "BMO Field",
        "city": "Toronto",
        "country": "Canada",
    },
    {
        "match_no": 35,
        "date": "2026-06-20",
        "time": "19:00",
        "stage": "Group E",
        "group": "E",
        "team1": "Ecuador",
        "team2": "Curaçao",
        "venue": "Arrowhead Stadium",
        "city": "Kansas City",
        "country": "USA",
    },
    {
        "match_no": 36,
        "date": "2026-06-20",
        "time": "22:00",
        "stage": "Group F",
        "group": "F",
        "team1": "Tunisia",
        "team2": "Japan",
        "venue": "Estadio BBVA",
        "city": "Guadalupe",
        "country": "Mexico",
    },

    # Sunday 21 June 2026
    {
        "match_no": 37,
        "date": "2026-06-21",
        "time": "12:00",
        "stage": "Group H",
        "group": "H",
        "team1": "Spain",
        "team2": "Saudi Arabia",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 38,
        "date": "2026-06-21",
        "time": "12:00",
        "stage": "Group G",
        "group": "G",
        "team1": "Belgium",
        "team2": "Iran",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },
    {
        "match_no": 39,
        "date": "2026-06-21",
        "time": "18:00",
        "stage": "Group H",
        "group": "H",
        "team1": "Uruguay",
        "team2": "Cape Verde",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },
    {
        "match_no": 40,
        "date": "2026-06-21",
        "time": "18:00",
        "stage": "Group G",
        "group": "G",
        "team1": "New Zealand",
        "team2": "Egypt",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },

    # Monday 22 June 2026
    {
        "match_no": 41,
        "date": "2026-06-22",
        "time": "12:00",
        "stage": "Group J",
        "group": "J",
        "team1": "Argentina",
        "team2": "Austria",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 42,
        "date": "2026-06-22",
        "time": "17:00",
        "stage": "Group I",
        "group": "I",
        "team1": "France",
        "team2": "Iraq",
        "venue": "Lincoln Financial Field",
        "city": "Philadelphia",
        "country": "USA",
    },
    {
        "match_no": 43,
        "date": "2026-06-22",
        "time": "20:00",
        "stage": "Group I",
        "group": "I",
        "team1": "Norway",
        "team2": "Senegal",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 44,
        "date": "2026-06-22",
        "time": "20:00",
        "stage": "Group J",
        "group": "J",
        "team1": "Jordan",
        "team2": "Algeria",
        "venue": "Levi's Stadium",
        "city": "Santa Clara",
        "country": "USA",
    },

    # Tuesday 23 June 2026
    {
        "match_no": 45,
        "date": "2026-06-23",
        "time": "12:00",
        "stage": "Group K",
        "group": "K",
        "team1": "Portugal",
        "team2": "Uzbekistan",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 46,
        "date": "2026-06-23",
        "time": "16:00",
        "stage": "Group L",
        "group": "L",
        "team1": "England",
        "team2": "Ghana",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },
    {
        "match_no": 47,
        "date": "2026-06-23",
        "time": "19:00",
        "stage": "Group L",
        "group": "L",
        "team1": "Panama",
        "team2": "Croatia",
        "venue": "BMO Field",
        "city": "Toronto",
        "country": "Canada",
    },
    {
        "match_no": 48,
        "date": "2026-06-23",
        "time": "20:00",
        "stage": "Group K",
        "group": "K",
        "team1": "Colombia",
        "team2": "DR Congo",
        "venue": "Estadio Akron",
        "city": "Zapopan",
        "country": "Mexico",
    },

    # Wednesday 24 June 2026
    {
        "match_no": 49,
        "date": "2026-06-24",
        "time": "12:00",
        "stage": "Group B",
        "group": "B",
        "team1": "Switzerland",
        "team2": "Canada",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },
    {
        "match_no": 50,
        "date": "2026-06-24",
        "time": "12:00",
        "stage": "Group B",
        "group": "B",
        "team1": "Bosnia and Herzegovina",
        "team2": "Qatar",
        "venue": "Lumen Field",
        "city": "Seattle",
        "country": "USA",
    },
    {
        "match_no": 51,
        "date": "2026-06-24",
        "time": "18:00",
        "stage": "Group C",
        "group": "C",
        "team1": "Scotland",
        "team2": "Brazil",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },
    {
        "match_no": 52,
        "date": "2026-06-24",
        "time": "18:00",
        "stage": "Group C",
        "group": "C",
        "team1": "Morocco",
        "team2": "Haiti",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 53,
        "date": "2026-06-24",
        "time": "19:00",
        "stage": "Group A",
        "group": "A",
        "team1": "Czechia",
        "team2": "Mexico",
        "venue": "Estadio Azteca",
        "city": "Mexico City",
        "country": "Mexico",
    },
    {
        "match_no": 54,
        "date": "2026-06-24",
        "time": "19:00",
        "stage": "Group A",
        "group": "A",
        "team1": "South Africa",
        "team2": "South Korea",
        "venue": "Estadio BBVA",
        "city": "Guadalupe",
        "country": "Mexico",
    },

    # Thursday 25 June 2026
    {
        "match_no": 55,
        "date": "2026-06-25",
        "time": "16:00",
        "stage": "Group E",
        "group": "E",
        "team1": "Curaçao",
        "team2": "Ivory Coast",
        "venue": "Lincoln Financial Field",
        "city": "Philadelphia",
        "country": "USA",
    },
    {
        "match_no": 56,
        "date": "2026-06-25",
        "time": "16:00",
        "stage": "Group E",
        "group": "E",
        "team1": "Ecuador",
        "team2": "Germany",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 57,
        "date": "2026-06-25",
        "time": "18:00",
        "stage": "Group F",
        "group": "F",
        "team1": "Japan",
        "team2": "Sweden",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 58,
        "date": "2026-06-25",
        "time": "18:00",
        "stage": "Group F",
        "group": "F",
        "team1": "Tunisia",
        "team2": "Netherlands",
        "venue": "Arrowhead Stadium",
        "city": "Kansas City",
        "country": "USA",
    },
    {
        "match_no": 59,
        "date": "2026-06-25",
        "time": "19:00",
        "stage": "Group D",
        "group": "D",
        "team1": "Turkey",
        "team2": "United States",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },
    {
        "match_no": 60,
        "date": "2026-06-25",
        "time": "19:00",
        "stage": "Group D",
        "group": "D",
        "team1": "Paraguay",
        "team2": "Australia",
        "venue": "Levi's Stadium",
        "city": "Santa Clara",
        "country": "USA",
    },

    # Friday 26 June 2026
    {
        "match_no": 61,
        "date": "2026-06-26",
        "time": "15:00",
        "stage": "Group I",
        "group": "I",
        "team1": "Norway",
        "team2": "France",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },
    {
        "match_no": 62,
        "date": "2026-06-26",
        "time": "15:00",
        "stage": "Group I",
        "group": "I",
        "team1": "Senegal",
        "team2": "Iraq",
        "venue": "BMO Field",
        "city": "Toronto",
        "country": "Canada",
    },
    {
        "match_no": 63,
        "date": "2026-06-26",
        "time": "18:00",
        "stage": "Group H",
        "group": "H",
        "team1": "Uruguay",
        "team2": "Spain",
        "venue": "Estadio Akron",
        "city": "Zapopan",
        "country": "Mexico",
    },
    {
        "match_no": 64,
        "date": "2026-06-26",
        "time": "19:00",
        "stage": "Group H",
        "group": "H",
        "team1": "Cape Verde",
        "team2": "Saudi Arabia",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 65,
        "date": "2026-06-26",
        "time": "20:00",
        "stage": "Group G",
        "group": "G",
        "team1": "Egypt",
        "team2": "Iran",
        "venue": "Lumen Field",
        "city": "Seattle",
        "country": "USA",
    },
    {
        "match_no": 66,
        "date": "2026-06-26",
        "time": "20:00",
        "stage": "Group G",
        "group": "G",
        "team1": "New Zealand",
        "team2": "Belgium",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },

    # Saturday 27 June 2026
    {
        "match_no": 67,
        "date": "2026-06-27",
        "time": "17:00",
        "stage": "Group L",
        "group": "L",
        "team1": "Panama",
        "team2": "England",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 68,
        "date": "2026-06-27",
        "time": "17:00",
        "stage": "Group L",
        "group": "L",
        "team1": "Croatia",
        "team2": "Ghana",
        "venue": "Lincoln Financial Field",
        "city": "Philadelphia",
        "country": "USA",
    },
    {
        "match_no": 69,
        "date": "2026-06-27",
        "time": "19:30",
        "stage": "Group K",
        "group": "K",
        "team1": "Colombia",
        "team2": "Portugal",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },
    {
        "match_no": 70,
        "date": "2026-06-27",
        "time": "19:30",
        "stage": "Group K",
        "group": "K",
        "team1": "DR Congo",
        "team2": "Uzbekistan",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 71,
        "date": "2026-06-27",
        "time": "21:00",
        "stage": "Group J",
        "group": "J",
        "team1": "Algeria",
        "team2": "Austria",
        "venue": "Arrowhead Stadium",
        "city": "Kansas City",
        "country": "USA",
    },
    {
        "match_no": 72,
        "date": "2026-06-27",
        "time": "21:00",
        "stage": "Group J",
        "group": "J",
        "team1": "Jordan",
        "team2": "Argentina",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },

    # ──────────────────────────────────────────────────────────────────
    # ROUND OF 32  (Matches 73–88)
    # Knockout teams are official FIFA bracket labels; actual teams TBD.
    # ──────────────────────────────────────────────────────────────────

    # Sunday 28 June 2026
    {
        "match_no": 73,
        "date": "2026-06-28",
        "time": "12:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group A runners-up",
        "team2": "Group B runners-up",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },

    # Monday 29 June 2026
    {
        "match_no": 74,
        "date": "2026-06-29",
        "time": "12:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group C winners",
        "team2": "Group F runners-up",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 75,
        "date": "2026-06-29",
        "time": "16:30",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group E winners",
        "team2": "Group A/B/C/D/F third place",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },
    {
        "match_no": 76,
        "date": "2026-06-29",
        "time": "19:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group F winners",
        "team2": "Group C runners-up",
        "venue": "Estadio BBVA",
        "city": "Guadalupe",
        "country": "Mexico",
    },

    # Tuesday 30 June 2026
    {
        "match_no": 77,
        "date": "2026-06-30",
        "time": "12:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group E runners-up",
        "team2": "Group I runners-up",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 78,
        "date": "2026-06-30",
        "time": "17:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group I winners",
        "team2": "Group C/D/F/G/H third place",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 79,
        "date": "2026-06-30",
        "time": "19:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group A winners",
        "team2": "Group C/E/F/H/I third place",
        "venue": "Estadio Azteca",
        "city": "Mexico City",
        "country": "Mexico",
    },

    # Wednesday 1 July 2026
    {
        "match_no": 80,
        "date": "2026-07-01",
        "time": "12:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group L winners",
        "team2": "Group E/H/I/J/K third place",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 81,
        "date": "2026-07-01",
        "time": "13:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group G winners",
        "team2": "Group A/E/H/I/J third place",
        "venue": "Lumen Field",
        "city": "Seattle",
        "country": "USA",
    },
    {
        "match_no": 82,
        "date": "2026-07-01",
        "time": "17:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group D winners",
        "team2": "Group B/E/F/I/J third place",
        "venue": "Levi's Stadium",
        "city": "Santa Clara",
        "country": "USA",
    },

    # Thursday 2 July 2026
    {
        "match_no": 83,
        "date": "2026-07-02",
        "time": "12:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group H winners",
        "team2": "Group J runners-up",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },
    {
        "match_no": 84,
        "date": "2026-07-02",
        "time": "19:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group K runners-up",
        "team2": "Group L runners-up",
        "venue": "BMO Field",
        "city": "Toronto",
        "country": "Canada",
    },
    {
        "match_no": 85,
        "date": "2026-07-02",
        "time": "20:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group B winners",
        "team2": "Group E/F/G/I/J third place",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },

    # Friday 3 July 2026
    {
        "match_no": 86,
        "date": "2026-07-03",
        "time": "13:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group D runners-up",
        "team2": "Group G runners-up",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 87,
        "date": "2026-07-03",
        "time": "18:00",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group J winners",
        "team2": "Group H runners-up",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },
    {
        "match_no": 88,
        "date": "2026-07-03",
        "time": "20:30",
        "stage": "Round of 32",
        "group": None,
        "team1": "Group K winners",
        "team2": "Group D/E/I/J/L third place",
        "venue": "Arrowhead Stadium",
        "city": "Kansas City",
        "country": "USA",
    },

    # ──────────────────────────────────────────────────────────────────
    # ROUND OF 16  (Matches 89–96)
    # ──────────────────────────────────────────────────────────────────

    # Saturday 4 July 2026
    {
        "match_no": 89,
        "date": "2026-07-04",
        "time": "12:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 73",
        "team2": "Winner Match 75",
        "venue": "NRG Stadium",
        "city": "Houston",
        "country": "USA",
    },
    {
        "match_no": 90,
        "date": "2026-07-04",
        "time": "17:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 74",
        "team2": "Winner Match 77",
        "venue": "Lincoln Financial Field",
        "city": "Philadelphia",
        "country": "USA",
    },

    # Sunday 5 July 2026
    {
        "match_no": 91,
        "date": "2026-07-05",
        "time": "16:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 76",
        "team2": "Winner Match 78",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
    {
        "match_no": 92,
        "date": "2026-07-05",
        "time": "18:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 79",
        "team2": "Winner Match 80",
        "venue": "Estadio Azteca",
        "city": "Mexico City",
        "country": "Mexico",
    },

    # Monday 6 July 2026
    {
        "match_no": 93,
        "date": "2026-07-06",
        "time": "14:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 83",
        "team2": "Winner Match 84",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },
    {
        "match_no": 94,
        "date": "2026-07-06",
        "time": "17:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 81",
        "team2": "Winner Match 82",
        "venue": "Lumen Field",
        "city": "Seattle",
        "country": "USA",
    },

    # Tuesday 7 July 2026
    {
        "match_no": 95,
        "date": "2026-07-07",
        "time": "12:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 86",
        "team2": "Winner Match 88",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },
    {
        "match_no": 96,
        "date": "2026-07-07",
        "time": "13:00",
        "stage": "Round of 16",
        "group": None,
        "team1": "Winner Match 85",
        "team2": "Winner Match 87",
        "venue": "BC Place",
        "city": "Vancouver",
        "country": "Canada",
    },

    # ──────────────────────────────────────────────────────────────────
    # QUARTER-FINALS  (Matches 97–100)
    # ──────────────────────────────────────────────────────────────────

    # Thursday 9 July 2026
    {
        "match_no": 97,
        "date": "2026-07-09",
        "time": "16:00",
        "stage": "Quarter-final",
        "group": None,
        "team1": "Winner Match 89",
        "team2": "Winner Match 90",
        "venue": "Gillette Stadium",
        "city": "Foxborough",
        "country": "USA",
    },

    # Friday 10 July 2026
    {
        "match_no": 98,
        "date": "2026-07-10",
        "time": "12:00",
        "stage": "Quarter-final",
        "group": None,
        "team1": "Winner Match 93",
        "team2": "Winner Match 94",
        "venue": "SoFi Stadium",
        "city": "Inglewood",
        "country": "USA",
    },

    # Saturday 11 July 2026
    {
        "match_no": 99,
        "date": "2026-07-11",
        "time": "17:00",
        "stage": "Quarter-final",
        "group": None,
        "team1": "Winner Match 91",
        "team2": "Winner Match 92",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },
    {
        "match_no": 100,
        "date": "2026-07-11",
        "time": "20:00",
        "stage": "Quarter-final",
        "group": None,
        "team1": "Winner Match 95",
        "team2": "Winner Match 96",
        "venue": "Arrowhead Stadium",
        "city": "Kansas City",
        "country": "USA",
    },

    # ──────────────────────────────────────────────────────────────────
    # SEMI-FINALS  (Matches 101–102)
    # ──────────────────────────────────────────────────────────────────

    # Tuesday 14 July 2026
    {
        "match_no": 101,
        "date": "2026-07-14",
        "time": "14:00",
        "stage": "Semi-final",
        "group": None,
        "team1": "Winner Match 97",
        "team2": "Winner Match 98",
        "venue": "AT&T Stadium",
        "city": "Arlington",
        "country": "USA",
    },

    # Wednesday 15 July 2026
    {
        "match_no": 102,
        "date": "2026-07-15",
        "time": "15:00",
        "stage": "Semi-final",
        "group": None,
        "team1": "Winner Match 99",
        "team2": "Winner Match 100",
        "venue": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "country": "USA",
    },

    # ──────────────────────────────────────────────────────────────────
    # THIRD-PLACE PLAY-OFF  (Match 103)
    # ──────────────────────────────────────────────────────────────────

    # Saturday 18 July 2026
    {
        "match_no": 103,
        "date": "2026-07-18",
        "time": "17:00",
        "stage": "Third-place play-off",
        "group": None,
        "team1": "Loser Match 101",
        "team2": "Loser Match 102",
        "venue": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "country": "USA",
    },

    # ──────────────────────────────────────────────────────────────────
    # FINAL  (Match 104)
    # ──────────────────────────────────────────────────────────────────

    # Sunday 19 July 2026
    {
        "match_no": 104,
        "date": "2026-07-19",
        "time": "15:00",
        "stage": "Final",
        "group": None,
        "team1": "Winner Match 101",
        "team2": "Winner Match 102",
        "venue": "MetLife Stadium",
        "city": "East Rutherford",
        "country": "USA",
    },
]

# ──────────────────────────────────────────────────────────────────────
# CONSISTENCY CHECKS
# ──────────────────────────────────────────────────────────────────────

REQUIRED_FIELDS = {"match_no", "date", "time", "stage", "group",
                   "team1", "team2", "venue", "city", "country"}

errors = []

# 1. Total count
if len(FIXTURES) != 104:
    errors.append(f"ERROR: Expected 104 fixtures, found {len(FIXTURES)}")

# 2. No duplicate match numbers
match_nos = [f["match_no"] for f in FIXTURES]
seen = set()
for n in match_nos:
    if n in seen:
        errors.append(f"ERROR: Duplicate match_no {n}")
    seen.add(n)

# 3. Sequential match numbers
expected = list(range(1, 105))
if match_nos != expected:
    missing = [n for n in expected if n not in seen]
    if missing:
        errors.append(f"ERROR: Missing match numbers: {missing}")

# 4. All required fields present
for f in FIXTURES:
    missing_keys = REQUIRED_FIELDS - f.keys()
    if missing_keys:
        errors.append(f"ERROR: Match {f.get('match_no')} missing fields: {missing_keys}")

# 5. Dates within tournament range
from datetime import date as _date
_start = _date(2026, 6, 11)
_end   = _date(2026, 7, 19)
for f in FIXTURES:
    d = _date.fromisoformat(f["date"])
    if not (_start <= d <= _end):
        errors.append(f"ERROR: Match {f['match_no']} date {f['date']} out of range")

# 6. Chronological ordering
dates = [f["date"] for f in FIXTURES]
if dates != sorted(dates):
    errors.append("ERROR: Fixtures are not in chronological order by date")

if errors:
    for e in errors:
        print(e)
else:
    print("All consistency checks passed.")

print(f"Total fixtures: {len(FIXTURES)}")
